### ISSUE TITLE
Sensitive data leak

### ISSUE THREAD

**Issue by cymruu** [Gwen1999/CS-GOMarketAnalyser#1]
[Do you know you leaked sensitive data like APIKEYS and secrets?](https://github.com/Gwen1999/CS-GOMarketAnalyser/blob/master/config/config.js#L3)
![image](https://cloud.githubusercontent.com/assets/2981598/24398874/42015eac-13ab-11e7-965c-03eba233e8c2.png)

You might find it interesting https://help.github.com/articles/removing-sensitive-data-from-a-repository/ ;)

**Comment by Gwen1999** [comment]
Oh shit well it's goot to know ahah i didn't expect any one to take a look at my project it was just for fun :/
thanks
